backend:
name: git-gateway
branch: sekolah
media_folder: "sekolah/images/uploads"
public_folder: "images/uploads"
collections:
  - name: "sekolah_data"
    label: "Data Sekolah"
    folder: "sekolah/data/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul Berita", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Foto Utama", name: "image", widget: "image"}
      - {label: "Isi Berita", name: "body", widget: "markdown"}
  - name: "profile_sekolah"
    label: "Tentang Sekolah"
    files:
      - label: "Visi Misi & Sambutan"
        name: "about"
        file: "sekolah/data/about.json"
        fields:
          - {label: "Nama Sekolah", name: "school_name", widget: "string"}
          - {label: "Nama Kepala Sekolah", name: "Kepsek", widget: "string"}
          - {label: "Foto Kepala Sekolah", name: "foto_Kepsek", widget: "image"}
          - {label: "Sambutan Kepala Sekolah", name: "greeting", widget: "text"}
          - {label: "Visi", name: "visi", widget: "text"}
          - {label: "Misi", name: "misi", widget: "list", field: {label: "Poin Misi", name: "item", widget: "string"}}
  - name: "data_guru"
    label: "Data Guru"
    folder: "sekolah/data/guru"
    create: true
    fields:
      - {label: "Nama Guru", name: "title", widget: "string"}
      - {label: "Jabatan/Mapel", name: "job", widget: "string"}
      - {label: "Foto Guru", name: "image", widget: "image"}
  - name: "kontak_sekolah"
    label: "Kontak dan Alamat"
    files:
      - label: "informasi kontak"
        name: "info_utama"
        file: "sekolah/data/kontak.json"
        fields:
          - {label: "Alamat Sekolah", name: "address", widget: "text"}
          - {label: "Nomor Telepon", name: "phone", widget: "string"}
          - {label: "Email Resmi", name: "email", widget: "string"}
        